name = "pure-genealogy"
main = ".open-next/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "zupu"
database_id = "6a0d57f5-0396-4356-aabc-ff1a1164db33"
migrations_dir = "lib/db/migrations"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "preview" }
