name = "genealogy-zupu"
main = ".vercel/output/static/index.html"

[[d1_databases]]
binding = "DB"
database_name = "zupu"
database_id = "6a0d57f5-0396-4356-aabc-ff1a1164db33"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "genealogy-assets"   # 请替换为你的 R2 桶名

[env.production]
vars = { JWT_SECRET = "your-secret" }
